spring:
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/big_event?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Aa@123456
  data:
    redis:
      host: 192.168.1.10
      port: 6379
      password: armbian@2025
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: itheima
  expiration: 43200000
